#!/usr/bin/env zsh

if [ $# -eq 1 ]; then
    echo "The bucket \"$1\" is going to be removed"
else
    echo "You provided $# arguments. Please provide exactly one argument."
    echo "E.g. ./delete-bucket my-bucket-name"
    exit -1
fi

aws s3api delete-bucket \
    --bucket $1
